@startuml TPA3-Clases

hide empty members

' Supermercado, Centro Comunal, Banco, ...
class Entidad {
  nombre: String
  tipoDeEntidad: TipoDeEntidad
  establecimientos: List<Establecimiento>
  usuariosInteresados: List<Usuario>
  incidentes: List<Incidente>
  --
  reportarIncidente(Servicio, String)
  notificarReporteDeIncidente(Incidente)
  getIncidentesAbiertos()
  getIncidentesResueltos()
}

Entidad <-r->"*" Establecimiento
Entidad -l->"*" Usuario
Entidad -u->"*" Incidente

' Sucursal, Estacion, ...
class Establecimiento {
  nombre: String
  servicios: List<Servicio>
  entidad: Entidad
  ubicacion: Ubicacion
  --
  tieneServicio(Servicio)
}

Establecimiento <->"*" Servicio
Establecimiento -d-> Ubicacion

class Servicio {
  descripcion: String
  establecimiento: Establecimiento
  tipoDeServicio: TipoDeServicio
}

class Usuario {
  usuario: String
  contraseña: String
  nombre: String
  apellido: String
  correoElectronico: String
  medioDeComunicacion: MedioDeComunicacion
  calendarioNotificaciones: CalendarioNotificaciones
  --
  getUbicacionActual(ServicioMapas)
  reportarIncidente(Servicio, String)
  cerrarIncidente(Comunidad, Incidente)
  notificarReporteDeIncidente(Incidente)
  sugerirRevisionDeIncidente(Incidente)
  notificar(Notificacion)
}

Usuario -l-> MedioDeComunicacion
Usuario -u-> CalendarioNotificaciones

class CalendarioNotificaciones {
  horarios: Map<DayOfWeek, RangoHorario>
  --
  abarcaA(LocalDateTime)
}

CalendarioNotificaciones -u-> RangoHorario

class RangoHorario {
  inicio: LocalTime
  fin: LocalTime
  --
  contieneHorario(LocalTime)
}

abstract MedioDeComunicacion {
  --
  notificar(Notificacion)
  procesarNotificacion(Notificacion)
}

class MedioWhatsApp extends MedioDeComunicacion {
  --
  procesarNotificacion(Notificacion)
}

class MedioEmail extends MedioDeComunicacion {
  --
  procesarNotificacion(Notificacion)
}

abstract Notificacion {
  usuario: Usuario
  fecha: LocalDateTime
  fechaEnvio: LocalDateTime
  --
  getAsunto()
  getMensaje()
}

class NotificacionNuevoIncidente extends Notificacion {
  incidente: Incidente
}

class NotificacionRevisionIncidente extends Notificacion {
  incidente: Incidente
}

MedioDeComunicacion .l.> Notificacion

class Comunidad {
  serviciosDeInteres: List<Servicio>
  incidentes: List<Incidente>
  miembros: List<Usuario>
  --
  reportarIncidente(Servicio, String, LocalDateTime, Usuario)
  cerrarIncidente(Incidente)
  notificarReporteDeIncidente(Incidente)
  getIncidentesAbiertos()
  getIncidentesAbiertosCercanosA(Usuario)
  getIncidentesResueltos()
  getMiembrosANotificar(Incidente)
}

Comunidad ->"*" Servicio
Comunidad -d->"*" Incidente
Comunidad -l->"*" Usuario

class Incidente {
  resuelto: boolean
  fecha: DateTime
  fechaResolucion: DateTime
  servicio: Servicio
  observaciones: String
  reportante: Usuario
  --
  cerrar()
  tiempoDeCierre()
}

Incidente -> Servicio
Incidente -l-> Usuario

class Ubicacion {
  latitud: double
  longitud: double
}

'interface ServicioMapas {
'  --
'  estanCerca(Ubicacion, Ubicacion, long): boolean
'  ubicacionActual(String): Ubicacion
'}

class OrganismoDeControl {
  nombre: String
  correoElectronico: String
  usuarioResponsable: Usuario
  entidadesControladas: List<Entidad>
  --
}

OrganismoDeControl -u->"entidadesControladas*" Entidad

/'

enum TipoDeServicio {
  ESCALERAS_MECANICAS
  ASCENSORES
  BAÑOS
}

Servicio -> TipoDeServicio

enum TipoDeEntidad {
  SUBTERRANEO
  FERROCARRIL
  SUPERMERADO
  BANCO
}

Entidad -> TipoDeEntidad

'/

@enduml