@startuml

left to right direction

actor "Administrador del sistema" as admin_sistema
actor "Usuario" as usuario
actor "Entidad/Organismo" as entidad

rectangle "Sistema" as system {
    usecase "Administración de entidades" as admin_entidades
    usecase "Administración de establecimientos" as admin_establecimientos
    usecase "Asignación de entidades de interés" as asignacion_intereses
    usecase "Asociación de localizaciones" as asociacion_localizaciones
    usecase "Asociación de localizaciones" as asociacion_localizaciones
    usecase "Administración de entidades prestadoras y organismos de control" as admin_entidades_organismos

    admin_sistema -- admin_entidades_organismos
    admin_sistema -- admin_entidades
    admin_sistema -- admin_establecimientos
    usuario -- asignacion_intereses
    usuario -- asociacion_localizaciones
    entidad -- asociacion_localizaciones
}

@enduml